### ISSUE TITLE
Proposal: Sync theme from remote source

### ISSUE THREAD

**Issue by with-heart** [chakra-ui/chakra-cli#4]
This proposal addresses some issues the existing cli has by introducing remote sources for theme files.

# Why?

`chakra-cli` currently faces the following problems:

- `templates` folders have to be manually updated whenever changes are made to the theme files in the main repo
  - this is annoying
  - we might forget!
- the theme version is synced to the cli version
  - this is error-prone
  - users have to install a specific version of the cli if they want to use the theme from a specific version of `@chakra-ui`

# Sources

In my mind, the remote sources are either tag-based `git`, release archives, or pre-compiled archives in the cloud. 

## `git`

The `git` source would allow users to specify a Chakra version that corresponds to a version tag in `git` to pull files from. JavaScript files would be transpiled from TS source at the time of the request.

## Release archives 

The release archives are automatically made available when a new release is made. This contains the source for the repo at the time of the version tag. It's probably an easier way to retrieve the files, though it still has the same need to transpile TS to JS at the time of the request.

## Cloud archives

The last alternative I have in mind is pre-compiled archives stored in the cloud. When a new Chakra version is published, a GitHub Action transpiles the TS theme files to JS, creates archives for both the TS and JS versions, and then pushes them to the cloud. This means that JS users no longer need to go through the transpilation step on request, as it has already been translated in advance.

# Future

This work could also allow us to open up the theme source to others, similar to the way `create-react-app` allows anyone to create their own template repos that others can use.

**Comment by segunadebayo** [comment]
I love this proposal @with-heart.

Ideally, I prefer if we use Github actions to sync the theme between the Chakra repo to Chakra CLI repo, and transpile to JS. 

Then we can look into allowing users to clone specific versions of the theme.

We also need to think about the scenario when we add new components to the theme, our users should be able to download only the updated component themes.

Lots of ideas here, we just need to prioritize and start working on them.

**Comment by with-heart** [comment]
Agreed. I'll start playing with this soon!

**Comment by with-heart** [comment]
I'm going to close this instead, since we're moving away from generating the theme using the cli.
